### ISSUE TITLE
setting enviroment variables

### ISSUE THREAD

**Issue by DENightOne** [t0bst4r/matterbridge-home-assistant#101]
I am having issues setting the environment variable for a manual install (no docker) as debian does not allow you to set environment  variables as json:
export HOME_ASSISTANT_CLIENT_CONFIG={ "includeDomains": ["light", "media_player"], "excludePatterns": ["media_player.*echo*"] }
 just produces errors and if i take all the spaces away is saves the variable but does not return the full variable.

Pretty sure I am doing something stupid and would appreciate being pointed in the right direction.
I for one would much prefer a single config file as in the docker implementation.

**Comment by t0bst4r** [comment]
Could you give it a try like that:

```bash
export HOME_ASSISTANT_CLIENT_CONFIG='{ "includeDomains": ["light", "media_player"], "excludePatterns": ["media_player.*echo*"] }'
```

There are two problems when exporting it without the `'`:
1. Those brackets `{}` are special characters in bash, which would not be parsed as the json string you need
2. Those `*` characters could be handled as globs, which will result in your env variable to not look as you expect 😁

**Comment by DENightOne** [comment]
thanks so much for the quick replay, that fixed it....I just need the ' '    I have a love/hate relationship with json..... well its more of a hate/hate relationship
