### ISSUE TITLE
Feature Request - Include/Exclude By Integration

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/matterbridge-home-assistant#109]
### Discussed in https://github.com/t0bst4r/matterbridge-home-assistant-addon/discussions/54

<div type='discussions-op-text'>

<sup>Originally posted by **meetheed** June 19, 2024</sup>
Loving the addon, great work. 

I recently set it up because i have a number of zigbee bulbs and switches controlled via the ZHA addon. And i wanted to expose these using Matter to Google Home / Alexa. This worked great. But i also have Philiips Hue bulbs. they have their own integration with google/alexa but they are also now being exposed using this addon. 

trying to exclude Hue but include ZHA in this addon doesnt seem to be stragiht forward, because both sets of lights belong to the "light" domain and the entity names ive been using dont identify the integration providing them so i also cant filter on a pattern.

Therefore i thought it maybe useful if we had an include / exclude that could filter via the "integration name"? This would allow people to select the entities that are exposed based on which integration provides them.

For now ive deleted the Hue integration from Google Home and Alexa and im using everyhting through this addon, but the Hue integration gives more control over the bulbs (colour pickers for example), so my preference in the long term would be to move back to using the officail Hue integration for Hue and this for others. </div>

**Comment by tevi** [comment]
Another enhancement on this include/exclude feature would be add devices via the labels feature that was introduced in homeassistant 2024.4. Given you can add multiple labels per device and you can set a label individually for each entity that gives a lot of fine grain control over which devices are added. Maybe even set a default label of "matterbridge" to include by default.

**Comment by tevi** [comment]
Not sure what the etiquette is for piling on variations of a feature enhancement on the same git issue, so I apologize if I'm violating the etiquette. 

Another enhancement for include/exclude is to increase the verbosity of the:

"Matterbridge] Added and registered bridged device (x/x) device name (mater device type) for plugin matterbridge-home-assistant" 

 statement in the logs. Currently it only shows the device name but the entity ID and matching rule will be helpful to debug which devices are included. I'm trying to only expose the devices I'll use via matter with this addon. I have several device with the same automatically generated name so it's difficult to figure out how to craft the glob patterns when I'm not entirely sure which entities are added.

**Comment by t0bst4r** [comment]
I would put that into another issue. But if you are running matterbridge-home-assistant in docker or local you could set the env-variable "LOG_DEBUG" to "true".

I'll refactor that in the future (that's why i didnt make it public), but for now it will put (at least) some things into debug mode. You'll see which entities are excluded, which are hidden, and what event is triggering a change (e.g. "brightness changed via matter", or "brightness changed via home assistant")

**Comment by t0bst4r** [comment]
This is implemented in the next release `2.1.0-98` (currently releasing - please wait 5 more minutes).
