### ISSUE TITLE
Lights brightness level and colors

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant#110]
## Problem
the domain lights has multiple kind of lights but they all shown like switches
> Why are you creating this issue?

## Expected behavior
should provide brightness level and color to supported lights

**Comment by genehand** [comment]
Hey I'm seeing something similar for Hue bulbs connected through Zigbee2mqtt, brightness is working but not the color settings.  Ah in my case it's because these are [ColorMode.xy lights](https://github.com/t0bst4r/matterbridge-home-assistant/blob/6bae9f72ade84bb4f752fa3482df83307d22a967/src/devices/aspects/color-control-aspect.ts#L16)

`OnOff: true Level: 204%`

```
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list: blink, breathe, okay, channel_change, candle, fireplace, colorloop, finish_effect, stop_effect, stop_hue_effect
supported_color_modes: color_temp, xy
effect: null
color_mode: color_temp
brightness: 204
color_temp_kelvin: 3636
color_temp: 275
hs_color: 27.048, 41.896
rgb_color: 255, 196, 148
xy_color: 0.444, 0.371
friendly_name: Nightstand
supported_features: 44
```
---

Here's an RGB one from a esphome controlled lightstrip:

`OnOff: true Hue: 19 Saturation: 122% Level: 224%`

```
min_color_temp_kelvin: 2700
max_color_temp_kelvin: 6000
min_mireds: 166
max_mireds: 370
effect_list: None, Pulse, Strobe, Random, Breathe, Color Breathe, Colorloop, Fiesta
supported_color_modes: color_temp, rgb
effect: None
color_mode: color_temp
brightness: 224
color_temp_kelvin: 3375
color_temp: 296
hs_color: 27.306, 47.56
rgb_color: 255, 188, 133
xy_color: 0.465, 0.376
icon: phu:light-strip
friendly_name: Office closet 
supported_features: 44
```

**Comment by t0bst4r** [comment]
Yes, it’s caused by xy color mode in your case. I didn’t know how to convert between HA xy values and matter xy values. Maybe I’ll do that in the next days.

**Comment by t0bst4r** [comment]
I just found [this](https://developers.home-assistant.io/docs/core/entity/light/#turn-on-light-device) in the docs of HA, saying that hs_color will be converted to rgb or xy whenever it is used with a light, which does not support hs. This would make things a lot easier, since i wouldn't need to convert to xy when controlling devices.
I'd only need to convert to hs when the state update comes from HA.

@genehand 
could you test what happens when you do the following service call on a light which only supports xy?
```yaml
service: light.turn_on
target:
  entity_id: light.my_light
data:
  xy_color: [0.291, 0.535]
```

**Comment by t0bst4r** [comment]
Just released xy support (without testing, just hoping, since i dont have such lights).
Please test it, and provide some feedback if it works.

**Comment by genehand** [comment]
Hmm, won't start up 😢 

```
Jun 30 11:14:49 chip matterbridge[7690]: file:///usr/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Device.js:164
Jun 30 11:14:49 chip matterbridge[7690]:     throw new ImplementationError("createOptionalClusterServer needs to be implemented by derived classes");
Jun 30 11:14:49 chip matterbridge[7690]:           ^
Jun 30 11:14:49 chip matterbridge[7690]: ImplementationError: createOptionalClusterServer needs to be implemented by derived classes
Jun 30 11:14:49 chip matterbridge[7690]:     at MatterbridgeDevice.createOptionalClusterServer (file:///usr/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Device.js:164:11)
Jun 30 11:14:49 chip matterbridge[7690]:     at MatterbridgeDevice.getClusterServer (file:///usr/lib/node_modules/matterbridge/node_modules/@project-chip/matter.js/dist/esm/device/Device.js:176:37)
Jun 30 11:14:49 chip matterbridge[7690]:     at get levelControlCluster [as levelControlCluster] (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:8:28)
Jun 30 11:14:49 chip matterbridge[7690]:     at LevelControlAspect.update (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:32:48)
Jun 30 11:14:49 chip matterbridge[7690]:     at LightDevice.updateState (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/devices/home-assistant-device.js:21:26)
Jun 30 11:14:49 chip matterbridge[7690]:     at async HomeAssistantMatterAdapter.create (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:91:9)
Jun 30 11:14:49 chip matterbridge[7690]:     at async HomeAssistantMatterAdapter.expensiveUpdate (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:45:13)
Jun 30 11:14:49 chip matterbridge[7690]:     at async HomeAssistantClient.expensiveUpdate (file:///usr/lib/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-client.js:50:13)
```

**Comment by t0bst4r** [comment]
Bug fix is on its way 🙈
Just fixed it on my mobile, so hoping it actually works. 😂

**Comment by genehand** [comment]
> Bug fix is on its way 🙈 Just fixed it on my mobile, so hoping it actually works. 😂

Haha cool I can test again.  

> could you test what happens when you do the following service call on a light which only supports xy?

The service call with `xy_color` is all good, as is `hs_color` so yeah I think it handles all the conversions.

**Comment by t0bst4r** [comment]
Release 1.5.1 is available. Could you try again?

**Comment by genehand** [comment]
Looks good in matterbridge now but Alexa is showing `Color Capabilities: None`

```
OnOff: true Hue: 19 Saturation: 92% Level: 255%
```

> I'd only need to convert to hs when the state update comes from HA.

Also don't know if this is universal but the 3 xy lights I have (2 hue, 1 sengled) have attributes for each type:

```
hs_color: 26.827, 35.453
rgb_color: 255, 205, 164
xy_color: 0.422, 0.366
```

**Comment by genehand** [comment]
Update: deleted the device in alexa to reset it.  Excluded in mb, restarted, then re-included and restarted again.  Came back with the same endpoint id but now it has `Color Capabilities: Color, Color Temperature` 🎉

**Comment by t0bst4r** [comment]
> Also don't know if this is universal but the 3 xy lights I have (2 hue, 1 sengled) have attributes for each type

Yes I have seen the same behaviors for virtual lights, but wouldn’t rely on that. Maybe in that case we could prefer hs but still fall back to the others.

ok, good to know that it works. Does also the color conversion match (roughly)? (The color Selected in Alexa vs the one assigned in HA)

**Comment by genehand** [comment]
Sorry missed this the other day, matches up great here with 1.5.2 🙌
