### ISSUE TITLE
Potential Bug: Error in the latest release v1.2.3

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#115]
Hi @t0bst4r 
The latest release 1.2.3, does not work (for me at least) I get the following error message in the logs:

```Failed to load plugin matterbridge-home-assistant: Error: ENOENT: no such file or directory, open '/app/node_modules/matterbridge-home-assistant/package.json'```

No entities are loaded or made available to Alexa.

Am I doing something wrong or is this a bug?

**Comment by t0bst4r** [comment]
How did you deploy your current setup?
Docker? Manual installation? Home Assistant Addon?

How did you upgrade from the previous version to the current?
Docker pull? Clicking the upgrade button in the UI? Clicking the upgrade button in Home Assistant Addon page?

**Comment by t0bst4r** [comment]
Ah yes, i've got the same error. This is caused by the persisted matterbridge config. The path of the installed files are stored there, but with the current version this path changed. I'll fix that.

**Comment by tam481** [comment]
I'm using docker compose.
Standalone docker container connecting to a Home Assistant container running on the same server. 

Reverting to v 1.2.1 fixes the issue.

Upgraded by pulling the latest image (ghcr.io/t0bst4r/matterbridge-home-assistant:latest) using docker compose pull then starting the contianer

**Comment by t0bst4r** [comment]
As a quick fix you could do the following:
1. open the Web UI
2. remove the matterbridge-home-assistant plugin
3. add the matterbridge-home-assistant plugin

BUT BE AWARE: that could de-register and then re-register all devices from your Alexa / Google Home.
In my case this caused Alexa to forget the room associations and routines for every device.

It would be better to stay at 1.2.1 for now. I'll remove the 1.2.3 docker release for now.

**Comment by t0bst4r** [comment]
i have added a workaround in the docker-entrypoint to update the plugin path. for me it worked like a charm 👍 

additionally i have upgraded to matterbridge 1.3.4 which prevents starting the whole bridge when a plugin fails at startup. This way it prevents devices to be deleted in the future.
