### ISSUE TITLE
[Feature]:  Device unavailability support

### ISSUE THREAD

**Issue by thewan056** [t0bst4r/matterbridge-home-assistant#141]
### Domain

All of them

### What is actually missing?

I would like to see some way of supporting unavailability. When devices that I expose using matterbridge-ha become unavailable in HA, it still shows up as the previous state, which is especially confusing if it was on before it became unavailable because it stays on in matterbridge and subsequently in Google Home which I use. 

If there is no support for showing devices as unavailable, I would like the option to have matterbridge detect if the device is unavailable in HA, then set its state to off if it was on previously, instead of leaving it on. 

In my case my devices being unavailable would be because a family member is using the existing dumb switches still wired to those devices instead of the actual device going offline. Setting their state to off would help to be less confusing since we assume we forgot to switch off some light and try to switch it off, but it doesn't do anything, it just stays as "On" in Google Home.

Of course I realize not everyone would like this behavior so that's why I hope it would become an option which I can add to my config.

**Comment by t0bst4r** [comment]
Good idea, i think the availability property is part of the data model. i'd need to check one or two things, but should be too difficult.

Having a lot todo at the moment, so please be patient with me 😁

**Comment by tammeryousef1006** [comment]
i think you can solve this from home assistant automation , matter support can show it as offline i guess

**Comment by t0bst4r** [comment]
Already had 5 minutes to do this. Just need to finalize it tomorrow 🙂

**Comment by t0bst4r** [comment]
just merged it.
it will be available in `1.6.0` in some minutes
