### ISSUE TITLE
[Bug]: door contact works opposite

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant#145]
### What happened?

i shared a door contact from xiaomi integration to matterbridge that paired to smartthings , the status works in opposite way , if the door were actually opened then at smartthings its appeared closed , if I close the door then at the app it shows that the door were opened , also battery still not exposed .

### Your configuration

offical home assistant addon 

### Version

1.5.2-73

**Comment by t0bst4r** [comment]
@bassrock have you already seen that before? Do you know if that’s default behavior in HA?
I could easily invert that by default, but I’m a bit afraid of breaking things for others 😅

**Comment by tammeryousef1006** [comment]
i never seen that before , is it  how to connect off to closed and on to open ?

**Comment by t0bst4r** [comment]
The binary sensor just reports "on" or "off".
The use case (in your case "door") gives it a meaning.
Our current implementation says „if it is not off, the contact sensor is true“.

But maybe this is wrong for contact sensors?
Could you provide the exact state value of your sensor (go to developer tools in HA, then to "states" and search the sensor by entity id) when the door is open and closed? Maybe also the entity id and attributes (also from the dev tools).

**Comment by tammeryousef1006** [comment]
![closed](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/abf77b57-e1b1-4eb3-85d8-dfa3cd6c5d49)
![off door](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/76761cb6-4c5d-4368-b8e8-d39d941fe108)

when its off it means closed , on is opened  , its door contact from xiaomi based on bluetooth

**Comment by tammeryousef1006** [comment]
![false](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/316bb136-a67b-43b6-8002-edf751a6f51b)

**Comment by tammeryousef1006** [comment]
now here is when its opened

![mb opened](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/5f2b7952-9470-4223-bc0d-6063b71192a7)
![opened xiaomi](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/f68a2df2-153b-487f-a44c-6bf32975c406)
![opened](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/1431e54b-c125-4bb5-9eb9-2f2a88dde469)

**Comment by t0bst4r** [comment]
Okay. As of now we have:

Door is open:
- In Home Assistant: `state: on`
- In Matter: `contact: true`
- In Google Home: `Closed`

Door is closed:
- in Home Assistant: `state: off`
- In Matter: `contact: false`
- In Google Home: `Open`

Semantically speaking I’d say it is correct to have `contact: true` when the door is closed.
So inverting the condition would be correct. 

But I’d like to verify that somehow - if that is the specified on/off behavior in HA as well.

**Comment by tammeryousef1006** [comment]
![Screenshot_20240702_233936_Home](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/b654388b-3ee7-474a-a5b8-78bde3df3dd6)
![Screenshot_20240702_233920_SmartThings](https://github.com/t0bst4r/matterbridge-home-assistant/assets/62266828/5038ce54-fd3f-4a1e-9b19-10025b102591)

At both smartthings and google home appears open while its closed

**Comment by t0bst4r** [comment]
Someone reported the same in #144

**Comment by Ultra-bob** [comment]
My issue is different, I have door open in home assistant (`on` state), but contact `on` in matterbridge, which would be closed, and is displayed by Google Home as such

**Comment by t0bst4r** [comment]
I just found this: 
https://www.home-assistant.io/integrations/binary_sensor/#device-class

So Austin with door, I’ll add all these one by one.
