### ISSUE TITLE
[Feature]: allow color temperature for lights not supporting color

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/matterbridge-home-assistant#146]
### Domain

Light

### What is actually missing?

Lights that only support temperature (not RGB) do not show any temperature control on Alexa. Matter Bridge exposes OnOff, levels clusters. If I add the same light through Nabu Casa integration Temperature is shown in Alexa.

[requested via HA community](https://community.home-assistant.io/t/act-as-a-matter-bridge/519019/42)

**Comment by JustDoneNow** [comment]
Experienced the same issue today. It would be great if you could take care of it.

**Comment by t0bst4r** [comment]
This should be fixed with version `2.0.3`.
