### ISSUE TITLE
[Feature]: Use Labels to Select Devices

### ISSUE THREAD

**Issue by jvmahon** [t0bst4r/matterbridge-home-assistant#210]
### Domain

All

### What is actually missing?

It would be really nice if there were more of a "fine-grained" way of selecting devices that are included or excluded from the bridge. 

I was thinking that HomeAssistant's new "Labels" feature might provide an easy solution. So, instead of (or in addition to), the "Include Patterns" in the dialog box, below, there was also a check box "Only Include devices labeled 'HomeBridge'" you could easily identify which devices to include. For example, if you included the domains light and switch, and then checked this box, it would also require that the device have the label "HomeBridge" in HomeAssistant.

![image](https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/15061942/250b9d9e-43a2-40ea-acfd-954435fe0a2d)

**Comment by t0bst4r** [comment]
Very good idea!
I'll put that on my to do list 😄

**Comment by jvmahon** [comment]
> Very good idea! I'll put that on my to do list 😄

Thank you!   I realize you must have a long list, so I tried to propose a simple solution. Hopefully, this is very simple code  (if entity does hot have label "MatterBridge" then skip ...).

The new Label feature is a a great way to tag HomeAssistant entities for purposes like this.

**Comment by t0bst4r** [comment]
This will be fixed in `2.1.0-98`. (currently releasing - please wait 5 more minutes)
