### ISSUE TITLE
[Bug]: Global npm modules in v2

### ISSUE THREAD

**Issue by genehand** [t0bst4r/matterbridge-home-assistant#214]
### What happened?

Hey I saw your comment on https://github.com/t0bst4r/matterbridge-home-assistant/issues/119 so I eagerly updated the config and upgraded. I then ran into the same error as https://github.com/t0bst4r/matterbridge-home-assistant/issues/59 for all devices:

```
Jul 24 14:42:48 chip matterbridge[3517]: [ 2024-07-24 14:42:48 ] [ error ] [ MatterConnector           ] Error: Only supported EndpointInterface implementation is Endpoint
Jul 24 14:42:48 chip matterbridge[3517]: [ 2024-07-24 14:42:48 ] [ warn ] [ MatterConnector           ] Failed to register device for light.office_closet
```

The workaround was to create a `package.json` for the deps and that's working for me now.  Should v2 still be compatible with the [global install instructions](https://github.com/t0bst4r/matterbridge-home-assistant/blob/main/packages/matterbridge-home-assistant/README.md#manual-setup)?

### Version

2.1.0

**Comment by t0bst4r** [comment]
Okay that is interesting 🤨 

If I do
```
npm install -g matterbridge matterbridge-home-assistant
```
it works, but if done in two steps (or installed via the UI) like this 
```
npm install -g matterbridge 
npm install -g matterbridge-home-assistant
```
I get the same error. 

Another (untested yet) workaround is to do `npm config set legacy-peer-deps true` or `export npm_legacy_peer_deps=true`. But then you also need to install `@project-chip/matter.js` and `@project-chip/matter-node.js`.

**Comment by t0bst4r** [comment]
For now I have added more details to the readme until I get an idea how to fix it properly.

**Comment by t0bst4r** [comment]
Finally got a solution for that. Both can be installed independently and we should not see the error anymore.
