### ISSUE TITLE
[Bug]: The plugin fails to start when using localhost config url.

### ISSUE THREAD

**Issue by gambalaya** [t0bst4r/matterbridge-home-assistant#245]
### What happened?

The plugin fails to start when using the localhost "url": "http://127.0.0.1:8123/". I tried this url first since my home assistant is on the same machine in host network mode. I got it working with the external interface url, so could be just a documentation note if not easy to handle. Nice plugin!

### Your configuration

Working config:
```
{
  "homeAssistant": {
    "url": "http://home.cvgadm:8123/",
    "accessToken": "redacted",
    "matcher": {
      "includeLabels": ["matter"]
    }
  }
}
```

vs Broken config:
```
{
  "homeAssistant": {
    "url": "http://127.0.0.1:8123/",
    "accessToken": "redacted",
    "matcher": {
      "includeLabels": ["matter"]
    }
  }
}
```

### Relevant log output

```shell
failed to start plugin "matterbridge-home-assistant": 1
```

### Version

2.4.0

**Comment by t0bst4r** [comment]
Hi @gambalaya ,
That’s a specialty of network interface (combined with docker). `localhost` and `127.0.0.1` are not leaving the docker container at all. Even in host network mode.
Its not a thing that’s under my control. I’ll add a note to the docs. 

So one needs to use the external IP (e.g. `192.168.178.23`) or the hostname (e.g. `my-raspi.local`).

**Comment by gambalaya** [comment]
Thanks @t0bst4r . I should have explained that _only_ my home assistant is in a docker container, and that I had used Manual Setup / Global installation with:
```
npm install -g matterbridge matterbridge-home-assistant
```
I verified localhost works when accessing home assistant from the same command prompt as "matterbridge -bridge" with curl:
```
curl - s \
-X GET \
-H "Authorization: Bearer redacted" \
-H "Content-Type: application/json" \
"http://127.0.0.1:8123/api/states/remote.bedroom"{
  "entity_id": "remote.bedroom",
  "state": "off",
  "attributes": {
    "activity_list": ["Watch TV"],
    "current_activity": "PowerOff",
    "activity_starting": null,
    "devices_list": ["Apple TV", "Samsung TV", "Pioneer AV Receiver"],
    "last_activity": null,
    "friendly_name": "Bedroom",
    "supported_features": 4
  },
  "last_changed": "2024-08-03T15:02:07.740527+00:00",
  "last_reported": "2024-08-03T15:02:07.740527+00:00",
  "last_updated": "2024-08-03T15:02:07.740527+00:00",
  "context": {
    "id": "01J4CC693W8FSGS4Q0RY09K0QH",
    "parent_id": null,
    "user_id": null
  }
}
```
Having said that, adding a hint to the docs not to use localhost is great too - thanks again.
