### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by marc3k18** [t0bst4r/matterbridge-home-assistant#29]
Hello!

Small question im new on Matter.  There is anyway to generate a certificat ? My hub dont want to connect to the plugin because of the certificat error.

**Comment by t0bst4r** [comment]
As far as I know, matter device can be certified, but it’s not like having a ssl certificate. It’s more like an official certification of the device. I don’t know if that is even possible for such a project, but anyway that’s more a topic for the [matterbridge project](https://github.com/Luligu/matterbridge).
