### ISSUE TITLE
Please support accessing Home Assistant via TLS

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#40]
Hello
Many thanks for creating this bridge. It's such a great feature for local control. I look forward to seeing it developed to become the defacto Matter bridge solution for HASS.

Please consider implementing TLS support for accessing HASS (Home Assistant)

**Comment by t0bst4r** [comment]
Thanks for your feedback.

Can you provide more details?
I am using a [library created by home assistant](https://www.npmjs.com/package/home-assistant-js-websocket) to connect to home assistant. This library seems to support https/wss.

Did you get any error message? Can you provide an error log? Did you use a custom self signed certificate for home assistant?

**Comment by tam481** [comment]
Thank you for the prompt response.
Yes I have HASS behind Traefik and I access it via https (443). When I tried to configure Matterbridge to connect to https://homeassistant.home.lan it simply failed with error:
`Failed to start plugin matterbridge-home-assistant: 1`

**Comment by t0bst4r** [comment]
I think I should add an option to set the log level in the dockerfile to show more details.

It seems that you are using a **self signed** certificate. Those certs are never accepted by anyone. You would need to either (1) disable ssl checks for the docker container or (2) add your own cert to the trust store.

1) try setting the env variable `NODE_TLS_REJECT_UNAUTHORIZED=0`. But i am not sure if the `ws` library considers this variable.

2)  you could try to mount your custom cert to any path in the container (e.g. `/cert`) and set the environment variable `NODE_EXTRA_CA_CERTS` to match the cert file path (e.g. `/cert/my-cert`).

please tell me if any of those worked.
In generell this is not a problem with matterbridge or matterbridge-home-assistant, but I’ll add a FAQ when we got it working with your setup.

**Comment by tam481** [comment]
Adding `NODE_TLS_REJECT_UNAUTHORIZED=0` has done the trick. I'm connected via Traefik just fine now. Thank you

**Comment by t0bst4r** [comment]
Okay 👌🏼 thank you for the feedback. I’ll add some hint to the readme or an extra faq page.

just to have it mentioned:

Setting the `NODE_TLS_REJECT_UNAUTHORIZED` variable, completely disables SSL verification for node.js. This is not recommended and definitely a security issue (man in the middle attacks are possible **if** they have access to your local network).

Actually it is nearly as bad as having no ssl at all. In some cases of **local** communication it’s fine to do - **if you know what you are doing**.

It is always better to tell the application about the self signed certificate it should trust. With that no man in the middle attack would be possible. On the other hand you need to do extra steps to configure that properly (option 2 of my previous post).
