### ISSUE TITLE
Excluding specific entities

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#42]
Hi @t0bst4r ,
I don't think it is currently possible to exclude specific entities. It is entirely possible that I have made a mistake but the following does not seem to work in my set up. If this is not currently possible, please consider implementing this when you get a chance.
```
{"includeDomains": ["light","switch"],"excludePatterns": ["media_player.*echo*","switch.power_socket_02","switch.corridor_lights","switch.kitchen_lights","switch.living_area_aqara_switch_power_outage_memory"]}
```

**Comment by t0bst4r** [comment]
Could you please format your config as code block to make sure GitHub doesn’t display it wrong.

Could you please provide the exact `docker run` command or `docker-compose.yaml`?
The matterbridge logs all devices it adds to the bridge. Please make sure that "wrong devices" are added. Can you provide the exact `entity_id` of one wrongly added entity?

**Comment by tam481** [comment]
Here's the docker compose code:

`  matterbridge:
    image: ghcr.io/t0bst4r/matterbridge-home-assistant:latest
    restart: unless-stopped
    container_name: matterbridge
    hostname: matterbridge
    volumes: 
      - "$PWD/../conf/matterbridge:/root/.matterbridge"
    network_mode: host
    env_file: "matterbridge.env"`

Here's the matterbridge.env file

`HOME_ASSISTANT_URL: "http://172.22.0.9:8123"
HOME_ASSISTANT_ACCESS_TOKEN: "redacted"
HOME_ASSISTANT_CLIENT_CONFIG: {"includeDomains": ["light","switch","media_player"],"excludePatterns": ["media_player.*echo*","switch.power_socket_02","switch.corridor_lights","switch.kitchen_lights","switch.living_area_aqara_switch_power_outage_memory"]}`

**Comment by t0bst4r** [comment]
Okay, thank you a lot. On the first sight everything looks good.

I’ll check that in detail tomorrow.

**Comment by tam481** [comment]
Hi @t0bst4r 
My apologies. I have managed to resolve this. It does work. There is no problem. The problem was that I have been adding the wrong type. The entities that keep reappearing were the wrong type. When I corrected this to switch like in the above instead of light it worked fine. I also forgot to re-create the container. All is working fine now :-)

**Comment by t0bst4r** [comment]
Okay! Thank you for letting me know.
