### ISSUE TITLE
Feature Request: Environment variables as config file instead

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#44]
Hi @t0bst4r ,
It would be great if you could make it so that the API key, URL and client config are loaded from a config file as well as the environmental variables. That way, one could write a config file in whatever format you prefer, json, yaml etc and just restart the container. At the moment I'm having to recreate the container every time I want to make a change.

Thank you

**Comment by t0bst4r** [comment]
Hi @tam481 ,
Loving that idea. I’ll definitely do that in the next days.

**Comment by t0bst4r** [comment]
If both are provided, what do you think who should win? Environment variable or config file?

**Comment by tam481** [comment]
I would say the config file as the user is most likely to edit the config file whereas the env variables might be the default settings if no config file is available.

Are you considering using JSON or YAML?

**Comment by t0bst4r** [comment]
Added to released version `0.5.0`.
