### ISSUE TITLE
Improvement: entities should match includeDomain OR includePatterns, not both

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#45]
Hi @t0bst4r 
With regards to  includePatterns option, am I correct in understanding with this option you can include specific supported entities?

If so, I can't seem to get it to work to load only a specific automation

`HOME_ASSISTANT_CLIENT_CONFIG: {"includeDomains": ["light","switch"],"includePatterns": ["automation.away_mode"],"excludePatterns": ["media_player.*echo*","switch.*echo*"]`

When I add the above it does not work. No entities are loaded.

If I remove the `,"includePatterns": ["automation.away_mode"]` everything works fine.

**Comment by t0bst4r** [comment]
Yes, I already got that feedback that the include props are not really useful how they work at the Moment.
Entities need to Match both, includeDomain AND include pattern. I should change it to "at least one of both". 

In your case you can work around that by removing includeDomains and only using the pattern with `light.*`, `switch.*` and `automation.away_mode` (additionally to the exclude patterns you have).

**Comment by t0bst4r** [comment]
Just implemented that with the Web editor using my mobile. I’ll review and test that myself tomorrow before releasing a new version 😆
