### ISSUE TITLE
Bug: Pairing with Alexa not possible with 100+ devices

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/matterbridge-home-assistant#53]
> Alexa pairing did not work when I had over 100 devices in the aggregator (Apple Home did)

https://community.home-assistant.io/t/act-as-a-matter-bridge/519019/33

**Comment by antoniozh** [comment]
With the new update, I placed my exclude list under the wrong JSON path and my Alexa bugged again for days before I found that I had 150 devices in the matter bridge. Maybe a warning would make sense?
