### ISSUE TITLE
Feature Request: Exclude hidden entities

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#54]
Hello
I've got some switch entities that I convert using helpers into light entities. This automatically hides the original switch entity but Matterbridge still loads them so I end up with the same entity twice as a switch and as a light entity. Please rectify if possible when you get a chance.

Many many thanks for working on this project :-)

**Comment by t0bst4r** [comment]
The original issue title was misleading, but it’s a duplicate of #52
