### ISSUE TITLE
Bug: Lost devices in Google Home if matterbridge-home-assistant starts before HA or before HA is fully loaded

### ISSUE THREAD

**Issue by Cheerpipe** [t0bst4r/matterbridge-home-assistant#55]
First of all, I am not sure if this is a bug or even if it belongs here or to the Matterbridge repository, so sorry if this bug report does not apply.

Description of the problem:

If Matterbridge-Home-Assistant (Docker version) is started before Home Assistant is running (or not fully loaded), it will "unregister" all devices, resulting in no devices being exposed. The problem is, if I am using Matterbridge devices with Google Home automations, these actions lose the link with the device, resulting in a "corrupted" automation. (Sorry for my English.)

Steps to reproduce:

1. Expose a device (e.g., a switch) using Matterbridge-Home-Assistant.
2. Link Google Home with Matterbridge-Home-Assistant.
3. Create a Google Home automation and add a switch turn-on action as the automation action. Until this point, everything works okay.
4. Stop Home Assistant.
5. Stop the Matterbridge-Home-Assistant Docker.
6. Start the Matterbridge-Home-Assistant Docker (before Home Assistant). At this point, Matterbridge-Home-Assistant will expose no devices.
7. Check the recent Google Home automations. The action parts will be empty.
8. I know Matterbridge-Home-Assistant is intended to be used with Home Assistant as a device backend, but the problem I describe above may occur anytime if Home Assistant is not up or not ready at the moment Matterbridge-Home-Assistant is started.

**Comment by t0bst4r** [comment]
That is interesting. I’ll try if it can be reproduced with Alexa as well.

in general all of this makes sense:
1. matterbridge starts with an empty bridge
2. Google home detects that the bridge is up again and scans it
3. Google removes all missing devices
4. automations loose references
5. Devices are added again

The difference with Alexa will be that devices are never removed when they disappear on the Bridge. They just get "unavailable".

The solution could be to cache entities in the storage and restore them on boot - before HA is contracted first. Anyway the removal of entities is one thing that wouldn’t  happen then. 

I’ll need to figure out how deletions of entities could be detected.

**Comment by Omnipius** [comment]
I'm experiencing similar behavior except it is happening on every restart of matterbridge. About 50% of my entities throw "New device added" messages on Google home every time matterbridge restarts, regardless of the started / loaded state of HA. The "new" devices lose their naming and room assignments...if they show up at all. Sometimes they're just gone and I have to restart again to get them back.

The devices that this happens to are consistent (same ones every time) but there's no discernable pattern. All of my entities are from the 'light' domain and most are from the same integration, so its not either of those. The craziest one is that there's one physical device with two independently controllable plugs: one is fine and stable, the other keeps reloading.

Thoughts?

**Comment by Omnipius** [comment]
No sooner do I post the above do I discover a distinction: 

When I look under my Android phone's Settings > Google > Devices & sharing > Matter devices
Stable devices are listed as: "Matter Devices Light"
Unstable devices are listed as: "Light (Vendor ID: 0000)"

**Comment by t0bst4r** [comment]
I've added a quick workaround, so that entities are initially loaded before matterbridge starts.
This will not fix the problem, when home assistant is not yet up, or other connectivity issues, but hopefully it will prevent google home from loosing the devices. After rebooting matterbridge.

**Comment by t0bst4r** [comment]
For the vendorId, i am not sure what happens in Google, Alexa or other controllers, when it changes.

**Comment by Omnipius** [comment]
I'm guessing changing VID and/or PID would be breaking for existing setups. Perhaps VID could be exposed as an optional config variable? That would at least enable testing. 

Ultimately what would be best is for matterbridge to have a full flight VID from the CSA, though I'm not sure how achievable that is.

**Comment by Omnipius** [comment]
I hunted down my issue as being caused by a particular Nest speaker. I blocked it from my network and now everything is stable. That speaker is unique, so I would let the Google/Nest devs worry about that.
