### ISSUE TITLE
Bug: Only supported EndpointInterface implementation is Endpoint

### ISSUE THREAD

**Issue by andrea689** [t0bst4r/matterbridge-home-assistant#59]
Hi, I start with "Manual Setup" and I receive these errors:

```
[10:35:25.732] [HomeAssistantPlatform] Failed to register device: light.luce_cucina 
[10:35:25.732] [HomeAssistantPlatform] Error: Only supported EndpointInterface implementation is Endpoint 
```

**Comment by t0bst4r** [comment]
Yes, i have seen that as well building the docker image.
This is related to how NPM installs peer dependencies for global modules.

I'll fix that, but before I have other bugs to fix and features to build 😁 .

# Workaround

As a workaround you could do the following:

1. Create an app directory wherever you want. This directory is used to store the `node_modules`.
2. Create a `package.json` file in your app dir with the following content:
```json
{
  "name": "my-matterbridge",
  "scripts": {
    "preserve": "matterbridge -add ./node_modules/matterbridge-home-assistant",
    "serve": "matterbridge -bridge"
  },
  "dependencies": {
    "matterbridge": "1.2.22",
    "matterbridge-home-assistant": "0.3.0"
  }
}
```
3. run `npm install` in your app directory
4. Run `npm run serve` in your app directory

**Comment by andrea689** [comment]
Many thanks, it works now!

For posterity, the globally installed plugin must first be removed:

```
matterbridge -remove matterbridge-home-assistant
```
