### ISSUE TITLE
Feature Request: add support for fans

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/matterbridge-home-assistant#70]

**Comment by genehand** [comment]
Adding some details as requested 😄  Poking through the code a little I realized we may need support in the main project first so checking on that.  Here's what I've dug up so far:

- matter.js docs for [FanControl](https://github.com/project-chip/matter.js/blob/main/docs/matter-node.js/interfaces/exports_cluster.FanControl.Cluster.md)
- Home assistant [fan service calls](https://github.com/home-assistant/core/blob/dev/homeassistant/components/fan/services.yaml)

I'm currently using node-red-matter with "dimmable outlets" where I translate the percentage setting into fan levels.  Works decently but would be nice to have a direct integration.

**Comment by genehand** [comment]
Fans are now supported in https://github.com/Luligu/matterbridge/releases/tag/1.3.0 👍

**Comment by t0bst4r** [comment]
Unfortunately Fans are not really supported by matterbridge or project-chip. They do not have any matter commands implemented which i could forward to home assistant. Additionally following the [list of ecosystems and supported device types](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#device-types-tested-on-various-ecosystems) most matter controllers do not support fans.

I have implemeneted fans using a dimmable on-off switch and level control for now.

**Comment by jvmahon** [comment]
As an FYI - the list of ecosystems and supported devices is definitely out of date. AT least Apple, SmartThings, and HomeAssistant now support Fans (I'm pretty sure Google does too).

Fans are an odd category Matter because they don't have "commands" like many other Matter devices, instead, they are controlled by writing to their attributes.

**Comment by genehand** [comment]
Working here 👍 

Only thing I noticed was this in the logs however it does set the level correctly:

```
Aug 03 08:17:02 chip matterbridge[3594]: 2024-08-03 08:17:02.061 DEBUG CommandServer Invoke moveToLevel with data {"level":241,"transitionTime":0,"optionsMask":{"executeIfOff":false,"coupleColorTempToLevel":false},"optionsOverride":{"executeIfOff":false,"coupleColorTempToLevel":false}}
Aug 03 08:17:02 chip matterbridge[3594]: 2024-08-03 08:17:02.069 DEBUG CommandServer Invoke moveToLevel response : "undefined"
```

**Comment by t0bst4r** [comment]
@jvmahon okay. But at least Alexa doesn’t support it. It doesn’t even show the fan device if device type is fan. 
Regarding the attributes and commands: How are we supposed to react to attribute changes through matter, if there are no command handlers? 😂
I don’t want to poll every second for attribute changes. 

@genehand i‘ll have a look, but since it’s a debug message just showing what’s happening I don’t see any problem with that.
