### ISSUE TITLE
Feature request: covers

### ISSUE THREAD

**Issue by rexhoffman** [t0bst4r/matterbridge-home-assistant#86]
covers (aka garage door openers) - looks like the would have a LevelControlAspect aspect like lights?
locks - looks like they would just have an on/off aspect?

This project is super slick and could be a great way to integrate myq (MyQ HomeKit Bridge -> home assistant -> matter bridge -> google home), among others.

**Comment by h4nnes** [comment]
Yes, would we cool if we could expose Home Assistant Cover entities :-)

**Comment by t0bst4r** [comment]
I've added (basic) support for locks. Please test and provide feedback.

**Comment by rexhoffman** [comment]
locks work well - tested in HomeKit, couldn't test in google home due to matter bridge bug.   Perhaps add battery support as well?   lock.<name> I believe will be back by sensor.<name>_battery_percentage from the smart locks I've had on home assistant.

**Comment by rexhoffman** [comment]
Tested in google home after following the bug to attach matterbridge to google home.  https://github.com/Luligu/matterbridge/issues/61, found that it works well via the app (no security pin like google often demands), but google assistant will not open the lock, trying to dig in to why.

**Comment by t0bst4r** [comment]
This was also requested by @Aaroneisele55 in https://github.com/t0bst4r/matterbridge-home-assistant-addon/issues/96

> ### Domain
> 
> cover
> 
> ### Attributes
> 
> ```shell
> cover.beschattung_b1
> closed
> 
> current_position: 100
> device_class: awning
> friendly_name: Beschattung Richtung Kienle
> supported_features: 255
> ```
> 
> 
> ### Services
> 
> ```shell
> # Close the cover
> service: cover.close_cover
> data: {}
> target:
>   entity_id: cover.beschattung_b1
> # Open the cover
> service: cover.open_cover
> data: {}
> target:
>   entity_id: cover.beschattung_b1
> # Set the position of the cover (0%-100%)
> service: cover.set_cover_position
> data:
>   position: 55
> target:
>   entity_id: cover.beschattung_b1
> # Stop the cover movement
> service: cover.stop_cover
> data: {}
> target:
>   entity_id: cover.beschattung_b1
> ```
> 
> 
> ### Version
> 
> 1.6.8-82
> 
> ### Additional comments
> 
> _No response_
>

**Comment by t0bst4r** [comment]
I have implemented basic support for covers. It will be released in about 5-10 minutes with version `2.3.0`.

Unfortunately i cannot test it, since i dont have any covers and i cannot find a way to add a virtual cover to home assistant.
So please test and provide feedback ❤️

**Comment by matthewdias** [comment]
@t0bst4r Works well so far for me in Google Home. Tested open, close, stop, set percentage

**Comment by t0bst4r** [comment]
Don’t you have any of those bugs as mentioned in #234 or #235 ?
If you have one of those please add a comment there to keep track. If not - just let me know somehow (here or in the other two issues).

**Comment by ivy-jhi** [comment]
> it also works fine for me in the Amazon system

Hi @Aaroneisele55 
Can you use the command open and close?
I can only set the cover per percentage.

**Comment by Aaroneisele55** [comment]
> > it also works fine for me in the Amazon system
> 
> Hi @Aaroneisele55 Can you use the command open and close? I can only set the cover per percentage.

I can't use open/close, but I made a routine as workaround that maps open/close to the percentages...

**Comment by h4nnes** [comment]
> > > it also works fine for me in the Amazon system
> > 
> > 
> > Hi @Aaroneisele55 Can you use the command open and close? I can only set the cover per percentage.
> 
> I can't use open/close, but I made a routine as workaround that maps open/close to the percentages...

It's seems to be inverted, at least for me. When I say "Alex open cover xxx" ---> the cover will be closed and vice versa

**Comment by Aaroneisele55** [comment]
> > > > it also works fine for me in the Amazon system
> > > 
> > > 
> > > Hi @Aaroneisele55 Can you use the command open and close? I can only set the cover per percentage.
> > 
> > I can't use open/close, but I made a routine as workaround that maps open/close to the percentages...
> 
> It's seems to be inverted, at least for me. When I say "Alex open cover xxx" ---> the cover will be closed and vice versa

I mapped open to 0 percent and close to 100 in a routine so it isn't inverted for me....

**Comment by t0bst4r** [comment]
Okay that’s what others are reporting as well of #234 
Thanks for the feedback. I’ll fix it on the weekend.
