### ISSUE TITLE
Filter not Working 

### ISSUE THREAD

**Issue by marc3k18** [t0bst4r/matterbridge-home-assistant#89]
include_domains:
  - light
  - switch
include_patterns:
  - light.gv_led_lumiere_ambiance_exterieur
  - light.sl_lamp_c*
  - switch.z2m_p_prise_exterieur
  - switch.z2m_wv*
exclude_domains: []
exclude_patterns: []

I should have 5 devices but I have 143 in matter bridge

**Comment by t0bst4r** [comment]
Entities need to match one of includePatterns or includeDomains, not both. I changed that some days ago (with another issue) to match the Alexa and apple home behavior. I forgot to update the readme, but just did it. 

Could you please check, if that’s the problem?
