### ISSUE TITLE
Feature Request: Support for Boolean_Input (Helpers)

### ISSUE THREAD

**Issue by tam481** [t0bst4r/matterbridge-home-assistant#96]
Hello
I've got a few boolean helpers for home/away, day time/night time which I use in my automations. It would be great to be able to switch these on/off (true/false really) to trigger automations.

I hope that this is something you would consider adding if at all possible?

Thank you in advance

**Comment by t0bst4r** [comment]
Can thy be turned on and off using `homeassistant.turn_on` and `homeassistant.turn_off` services?

Is the value of the state `on` and `off`?

If both questions are answered with yes, it‘ll be very easy. If not, it will be probably still be easy, but I’d need the correct services and states.

**Comment by tam481** [comment]
Would this work?

`service: input_boolean.turn_off
metadata: {}
data: {}
target:
  entity_id: input_boolean.device_helper`

**Comment by tam481** [comment]
I have also checked and it is possible to do with homeassistant.turn_on and homeassistant.turn_off

**Comment by t0bst4r** [comment]
If you are using the home assistant addon, i'll just need one or two more days to setup a proper release flow. I'll add another comment, when this is released there.
